
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
#   @author         :   Chris Burnham
#   @file           :   ~/.config/Homebrew/Brewfile
#   @description    :   Brewfile - one file to rule them all
#   @usage          :   brew bundle --file "$HOME/.config/Homebrew/Brewfile"
# ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

